name: Get Google Drive Data And Transform

on:
  workflow_dispatch:
  schedule:
    - cron: '02 * * * *'
permissions:
  contents: write

jobs:
  Get-Google-Drive-Data-And-Transform:
    name: Get Google Drive Data And Transform
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      GDRIVE_OPP_MAP_SECRET: ${{ secrets.GDRIVE_OPP_MAP_SECRET }}
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v1
      - name: Install libcurl and libssl on Linux
        run: 'sudo apt-get -y install libcurl4-openssl-dev'
        shell: bash
      - name: Install CRAN packages
        run: Rscript -e 'install.packages(c("tidyr", "dplyr", "googledrive", "googlesheets4"))'
      - name: Run GoogleDrive R script
        run: |
          source('gdocs data transform script.R')
        shell: Rscript {0}
      - name: Commit results
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add data 
          git commit -m 'Data transformed _ TEST' || echo "No changes to commit"
          git push origin || echo "No changes to commit"
