name: Get Google Drive Data And Transform

on:
  workflow_dispatch:
  schedule:
    - cron: '43 18 * * *'
permissions:
  contents: write

jobs:
  Get-Google-Drive-Data-And-Transform:
    name: Get Google Drive Data And Transform
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      GDRIVE_OPP_MAP_SECRET: ${{ secrets.GDRIVE_OPP_MAP_SECRET }}
      
    steps:
    - name: Check out GH repository
      uses: actions/checkout@v4
      
    - name: Set up R
      uses: r-lib/actions/setup-r@v2
      with:
        use-public-rspm: true
        
    - name: Install libcurl and libssl on Linux
      run: 'sudo apt-get -y install libcurl4-openssl-dev'
      shell: bash
      
    - name: Install CRAN packages
      run: Rscript -e 'install.packages(c("tidyr", "dplyr", "googledrive", "googlesheets4"))'
    - name: Run GoogleDrive R script
      run: Rscript "gdocs data transform script.R"

