name: Get Google Drive Data And Transform

on:
  schedule:
    - cron: '10 * * * *'

jobs:
  Get-Google-Drive-Data-And-Transform:
    name: Get Google Drive Data And Transform
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GDRIVE_OPP_MAP_SECRET }}
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v1
      - name: Install libcurl and libssl on Linux
        run: 'sudo apt-get -y install libcurl4-openssl-dev'
        shell: bash
      - name: Install CRAN packages
        run: Rscript -e 'install.packages(c("tidyverse", "googledrive", "googlesheets4"))'
      - name: Run GoogleDrive R script
        run: |
          source('scripts/Get-GoogleDrive-Data.R')
        shell: Rscript {0}
      - name: Run basic plot script
        run: |
          source('scripts/Plot-ggplot.R')
        shell: Rscript {0}
      - name: Commit results
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add data 
          git add basic_plots
          git commit -m 'Data download and create basic plot. TEST' || echo "No changes to commit"
          git push origin || echo "No changes to commit"
