name: Get Google Drive Data And Transform

on:
  workflow_dispatch:
  schedule:
    - cron: '*/5 * * * *'
permissions:
  contents: write

jobs:
  Get-Google-Drive-Data-And-Transform:
    name: Get Google Drive Data And Transform
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      GDRIVE_OPP_MAP_SECRET: ${{ secrets.GDRIVE_OPP_MAP_SECRET }}
      
    steps:
    - name: Check out GH repository
      uses: actions/checkout@v4
      
    - name: Set up R
      uses: r-lib/actions/setup-r@v2
      with:
        use-public-rspm: true
        
    - name: Install libcurl and libssl on Linux
      run: 'sudo apt-get -y install libcurl4-openssl-dev'
      shell: bash
    - name: Install CRAN packages
      run: Rscript -e 'install.packages(c("tidyr", "dplyr", "googledrive", "googlesheets4"))'
    - name: Run GoogleDrive R script
      run: |
        source('gdocs data transform script.R')
      shell: Rscript {0}
    - name: Commit results
      run: |
        git config --local user.email "actions@github.com"
        git config --local user.name "GitHub Actions"
        git add data 
        git commit -m 'Data transformed _ TEST' || echo "No changes to commit"
        git push origin || echo "No changes to commit"
